services:
  postgres:
    image: postgres
    container_name: postgres
    command: -p 5435
    ports:
      - '6500:5432'
    restart: always
    env_file:
      - .env
    volumes:
      - postgres-db:/var/lib/postgresql/data
volumes:
  postgres-db: